### PR TITLE
Fix size_t/uint32_t conversion warning, cppcheck 1.66 fix

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by rdumusc** [comment]
Oh, I was about to send a mail to enquire about this unit test failing in viz/latest - but it seems you already looked into it :-)

**Comment by tribal-tec** [comment]
This is just a compiler warning happening with MSVC. Should not change anything wrt test execution. It's green here anyways :)

**Comment by rdumusc** [comment]
Oh... :-( 
Then any idea about this? FAILED: cd /gpfs/bbp.cscs.ch/home/bbprelman/jenkins-cscs-01/workspace/viz.latest/platform/cscsviz/release/Collage/tests && /gpfs/bbp.cscs.ch/apps/viz/bbp/dev/cmake/3.2.3/bin/ctest -Q -T test --no-compress-output -R '^barrierException$' -C Release

**Comment by rdumusc** [comment]
unit test passed at the next viz/stable run. Forget about that for now.

**Pull request merged**
