### PR TITLE
Add support for distributable ZeroBuf object, cleanups

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by eile** [comment]
+1

Zerobuf only needs to be pulled in for the unit test... Seems a bit heavy weight, although I don't have an alternative.

**Comment by tribal-tec** [comment]
The subproject clone could be removed, so the test only is executed in a super project build which contains ZeroBuf.

**Comment by tribal-tec** [comment]
retest this please

**Comment by tribal-tec** [comment]
retest this please

**Pull request merged**
