### PR TITLE
Fixed two issues with RDMA connection establishment.

### PR DESCRIPTION
**Pull request by hernando**
In some systems rdma_getaddrinfo returns a list of addresses where
the first is from the AF_IB familiy. Apparently this only happens
in the client and the server, which binds using AF_INET[6] rejects
the connection.

In route resolution it is necessary to wait for the event
RDMA_CM_EVENT_ROUTE_RESOLVED fter using rdma_set_option when the
rdma_addrinfo struct contains routing information.

### CODE REVIEW

**Comment by hernando** [comment]
FYI @dardok

**Comment by hernando** [comment]
Retest this please.

**Comment by hernando** [comment]
@eile, @tribal-tec could you review?

**Comment by tribal-tec** [comment]
Good to me, although I'm not an expert here.

**Pull request merged**
