### PR TITLE
	Fix test race

### PR DESCRIPTION
**Pull request by eile**
Should fix https://bbpcode.epfl.ch/ci/job/viz.RTNeuron/build_type=Debug,platform=Ubuntu-14.04/1491/changes

### CODE REVIEW

**Comment by eile** [comment]
ping?

**Comment by hernando** [comment]
I didn't have time to look at it yet.

**Comment by hernando** [comment]
You'll have to explain it to me in person. Without investing too much time looking at the full code I can't understand the implications of those "innocent" changes.

**Comment by hernando** [comment]
Doesn't compile

**Pull request merged**
